
import javax.swing.JOptionPane;

/**
 GUI - The graphical user interface for our math expression calculator.

 @author C3C Jared Peterson
 @author C3C Gavin Delphia
 @version 1.0 - Mar 20, 2012 at 5:56:08 PM

 Documentation: C3C Jared Peterson and C3C Gavin Delphia completed this
 assignment together without help from any outside sources except EI with Dr. Bower.
 */
public class GUI extends javax.swing.JFrame {

  /**
   Creates new form GUI
   */
  public GUI() {
    initComponents();
  }

  /**
   This method is called from within the constructor to initialize the
   form. WARNING: Do NOT modify this code. The content of this method is
   always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about_dialog = new javax.swing.JDialog();
        about_scrollpane = new javax.swing.JScrollPane();
        about_textarea = new javax.swing.JTextArea();
        expression_field = new javax.swing.JTextField();
        backspace_button = new javax.swing.JButton();
        c_button = new javax.swing.JButton();
        seven_button = new javax.swing.JButton();
        eight_button = new javax.swing.JButton();
        nine_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        leftp_button = new javax.swing.JButton();
        four_button = new javax.swing.JButton();
        five_button = new javax.swing.JButton();
        six_button = new javax.swing.JButton();
        multi_button = new javax.swing.JButton();
        rightp_button = new javax.swing.JButton();
        one_button = new javax.swing.JButton();
        two_button = new javax.swing.JButton();
        three_button = new javax.swing.JButton();
        sub_button = new javax.swing.JButton();
        zero_button = new javax.swing.JButton();
        point_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        equals_button = new javax.swing.JButton();
        main_menu = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        exit_option = new javax.swing.JMenuItem();
        edit_menu = new javax.swing.JMenu();
        copy_option = new javax.swing.JMenuItem();
        paste_option = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        about_option = new javax.swing.JMenuItem();

        about_dialog.setTitle("About");
        about_dialog.setAlwaysOnTop(true);
        about_dialog.setBounds((java.awt.Toolkit.getDefaultToolkit().getScreenSize().width-400)/2, (java.awt.Toolkit.getDefaultToolkit().getScreenSize().height-160)/2, 400, 160);
        about_dialog.setIconImage(null);
        about_dialog.setModal(true);
        about_dialog.setResizable(false);

        about_textarea.setBackground(new java.awt.Color(240, 240, 240));
        about_textarea.setColumns(20);
        about_textarea.setEditable(false);
        about_textarea.setRows(5);
        about_textarea.setText("Expression Calculator\n\nCreated by Jared Peterson and Gavin Delphia\n20 Mar 2012\n");
        about_textarea.setMinimumSize(null);
        about_scrollpane.setViewportView(about_textarea);

        javax.swing.GroupLayout about_dialogLayout = new javax.swing.GroupLayout(about_dialog.getContentPane());
        about_dialog.getContentPane().setLayout(about_dialogLayout);
        about_dialogLayout.setHorizontalGroup(
            about_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(about_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(about_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        about_dialogLayout.setVerticalGroup(
            about_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(about_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(about_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expression Calculator");
        setResizable(false);

        expression_field.setEditable(false);
        expression_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expression_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        expression_field.setRequestFocusEnabled(false);

        backspace_button.setText("Back Space");
        backspace_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspace_buttonActionPerformed(evt);
            }
        });

        c_button.setText("C");
        c_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_buttonActionPerformed(evt);
            }
        });

        seven_button.setText("7");
        seven_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_buttonActionPerformed(evt);
            }
        });

        eight_button.setText("8");
        eight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_buttonActionPerformed(evt);
            }
        });

        nine_button.setText("9");
        nine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_buttonActionPerformed(evt);
            }
        });

        divide_button.setText("/");
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });

        leftp_button.setText("(");
        leftp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftp_buttonActionPerformed(evt);
            }
        });

        four_button.setText("4");
        four_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_buttonActionPerformed(evt);
            }
        });

        five_button.setText("5");
        five_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_buttonActionPerformed(evt);
            }
        });

        six_button.setText("6");
        six_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_buttonActionPerformed(evt);
            }
        });

        multi_button.setText("*");
        multi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi_buttonActionPerformed(evt);
            }
        });

        rightp_button.setText(")");
        rightp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightp_buttonActionPerformed(evt);
            }
        });

        one_button.setText("1");
        one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_buttonActionPerformed(evt);
            }
        });

        two_button.setText("2");
        two_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_buttonActionPerformed(evt);
            }
        });

        three_button.setText("3");
        three_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_buttonActionPerformed(evt);
            }
        });

        sub_button.setText("-");
        sub_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_buttonActionPerformed(evt);
            }
        });

        zero_button.setText("0");
        zero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_buttonActionPerformed(evt);
            }
        });

        point_button.setText(".");
        point_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point_buttonActionPerformed(evt);
            }
        });

        add_button.setText("+");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        equals_button.setText("=");
        equals_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equals_buttonActionPerformed(evt);
            }
        });

        file_menu.setText("File");
        file_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                file_menuMouseClicked(evt);
            }
        });

        exit_option.setText("Exit");
        exit_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_optionActionPerformed(evt);
            }
        });
        file_menu.add(exit_option);

        main_menu.add(file_menu);

        edit_menu.setText("Edit");
        edit_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_menuMouseClicked(evt);
            }
        });
        edit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_menuActionPerformed(evt);
            }
        });

        copy_option.setText("Copy");
        copy_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_optionActionPerformed(evt);
            }
        });
        edit_menu.add(copy_option);

        paste_option.setText("Paste");
        paste_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paste_optionActionPerformed(evt);
            }
        });
        edit_menu.add(paste_option);

        main_menu.add(edit_menu);

        help_menu.setText("Help");

        about_option.setText("About");
        about_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_optionActionPerformed(evt);
            }
        });
        help_menu.add(about_option);

        main_menu.add(help_menu);

        setJMenuBar(main_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(five_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(six_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sub_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(point_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equals_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(expression_field, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(backspace_button, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_button, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(multi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rightp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leftp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expression_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspace_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(five_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(six_button, javax.swing.GroupLayout.DEFAULT_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multi_button, javax.swing.GroupLayout.DEFAULT_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rightp_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(equals_button, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents
  public boolean hasPoint = false;
  public boolean negLast = false;
  public boolean symLast = false;
  public String saved = "";

  private void exit_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_optionActionPerformed
    System.exit(0);
  }//GEN-LAST:event_exit_optionActionPerformed

  private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_buttonActionPerformed
    addToExpression("/");
  }//GEN-LAST:event_divide_buttonActionPerformed

  private void file_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_file_menuMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_file_menuMouseClicked

  private void edit_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_menuMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_edit_menuMouseClicked

  private void about_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_optionActionPerformed
    about_dialog.setVisible(true);
  }//GEN-LAST:event_about_optionActionPerformed

  private void equals_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equals_buttonActionPerformed
    try {
      ExpressionTree tree = new ExpressionTree(expression_field.getText());
      expression_field.setText(tree.evaluate() + "");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e.getClass().getName() + " " + e.getMessage());
    }
  }//GEN-LAST:event_equals_buttonActionPerformed

  private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
    addToExpression("+");
  }//GEN-LAST:event_add_buttonActionPerformed

  private void point_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point_buttonActionPerformed
    addToExpression(".");
  }//GEN-LAST:event_point_buttonActionPerformed

  private void zero_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_buttonActionPerformed
    addToExpression(0);
  }//GEN-LAST:event_zero_buttonActionPerformed

  private void sub_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_buttonActionPerformed
    if (symLast || expression_field.getText().length() == 0) {
      addToExpression("Neg");
    } else {
      addToExpression("-");
    }
  }//GEN-LAST:event_sub_buttonActionPerformed

  private void three_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_buttonActionPerformed
    addToExpression(3);
  }//GEN-LAST:event_three_buttonActionPerformed

  private void two_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_buttonActionPerformed
    addToExpression(2);
  }//GEN-LAST:event_two_buttonActionPerformed

  private void six_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_buttonActionPerformed
    addToExpression(6);
  }//GEN-LAST:event_six_buttonActionPerformed

  private void five_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_buttonActionPerformed
    addToExpression(5);
  }//GEN-LAST:event_five_buttonActionPerformed

  private void four_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_buttonActionPerformed
    addToExpression(4);
  }//GEN-LAST:event_four_buttonActionPerformed

  private void leftp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftp_buttonActionPerformed
    addToExpression("(");
  }//GEN-LAST:event_leftp_buttonActionPerformed

  private void nine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_buttonActionPerformed
    addToExpression(9);
  }//GEN-LAST:event_nine_buttonActionPerformed

  private void eight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_buttonActionPerformed
    addToExpression(8);
  }//GEN-LAST:event_eight_buttonActionPerformed

  private void seven_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_buttonActionPerformed
    addToExpression(7);
  }//GEN-LAST:event_seven_buttonActionPerformed

  private void c_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_buttonActionPerformed
    resetExpression();
  }//GEN-LAST:event_c_buttonActionPerformed

  private void backspace_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspace_buttonActionPerformed
    backspaceExpression();
  }//GEN-LAST:event_backspace_buttonActionPerformed

  private void edit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_menuActionPerformed
  }//GEN-LAST:event_edit_menuActionPerformed

  private void copy_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_optionActionPerformed
    saved = expression_field.getText();
  }//GEN-LAST:event_copy_optionActionPerformed

  private void paste_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paste_optionActionPerformed
    expression_field.setText(saved);
  }//GEN-LAST:event_paste_optionActionPerformed

  private void one_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_buttonActionPerformed
    addToExpression(1);
  }//GEN-LAST:event_one_buttonActionPerformed

  private void rightp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightp_buttonActionPerformed
    addToExpression(")");
  }//GEN-LAST:event_rightp_buttonActionPerformed

  private void multi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi_buttonActionPerformed
    addToExpression("*");
  }//GEN-LAST:event_multi_buttonActionPerformed

  /**
   Resets the expression to empty
   */
  public void resetExpression() {
    expression_field.setText("");
    negLast = false;
    hasPoint = false;
    symLast = false;
  }

  /**
   Removes the last input of the expression
   */
  public void backspaceExpression() {
    String expression = expression_field.getText();
    int expression_length = expression_field.getText().length();
    if (expression_length >= 2) {
      String second_last = expression_field.getText().charAt(expression_length - 2) + "";
      if (second_last.equalsIgnoreCase(" ")) {
        expression = expression.substring(0, expression_length - 2);
      } else if (second_last.equalsIgnoreCase("-")) {
        if (expression_length >= 3) {
          expression = expression.substring(0, expression_length - 3);
        } else {
          expression = expression.substring(0, expression_length - 2);
        }
      } else {
        expression = expression.substring(0, expression_length - 1);
      }
    } else {
      if (expression_length != 0) {
        expression = expression.substring(0, expression_length - 1);
      }
    }
    negLast = false;
    expression_field.setText(expression);
  }

  /**
   Adds operators to the expression

   @param current the operator to add to the expression
   */
  public void addToExpression(String current) {
    String spaceB = " ";
    String spaceA = " ";
    int expression_length = expression_field.getText().length();
    String last;

    if (expression_length != 0) {
      last = expression_field.getText().charAt(expression_length - 1) + "";

      //prevent multiple repeating negatives
      if (last.equalsIgnoreCase("-") && current.equalsIgnoreCase("Neg")) {
        return;
      }

      //prevent multiple repeating negatives
      if (last.equalsIgnoreCase("-") && current.equalsIgnoreCase("-")) {
        return;
      }

      //prevent double points
      if (last.equalsIgnoreCase(".") && current.equalsIgnoreCase(".")) {
        return;
      }

    }

    //Only able to lead with neg or point or (
    if ((expression_length == 0 && !current.equalsIgnoreCase("Neg")) && (expression_length == 0 && !current.equalsIgnoreCase("."))
        && (expression_length == 0 && !current.equalsIgnoreCase("(")) && (expression_length == 0)) {
      return;
    }

    if (symLast) {

      //prevent duplicate operators
      if (current.equalsIgnoreCase("+") || current.equalsIgnoreCase("*") || current.equalsIgnoreCase("/")) {
        return;
      }

      //prevent operators after a point
      if (hasPoint) {
        if (current.equalsIgnoreCase("-") || current.equalsIgnoreCase("(") || current.equalsIgnoreCase(")") || current.equalsIgnoreCase("Neg")) {
          return;
        }
      }

      spaceB = "";
    }


    symLast = true;
    if (current.equalsIgnoreCase(")") || current.equalsIgnoreCase("(")) {
      symLast = false;
    }
    if (current.equalsIgnoreCase("Neg")) {
      current = "-";
      negLast = true;
      spaceA = "";
    } else if (current.equalsIgnoreCase(".")) {
      hasPoint = true;
      spaceA = spaceB = "";
    } else {
      hasPoint = false;
    }

    expression_field.setText(expression_field.getText() + spaceB + current + spaceA);
  }

  /**
   Adds numbers to the expression

   @param current the number to add to the expression
   */
  public void addToExpression(int current) {
    symLast = false;
    negLast = false;
    expression_field.setText(expression_field.getText() + current);
  }

  /**
   @param args the command line arguments
   */
  public static void main(String args[]) {
//    /*
//     Set the look and feel
//     */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//     If Nimbus (introduced in Java SE 6) is not available, stay with the
//     default look and feel. For details see
//     http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
    try {
      javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
      // Ignore exceptions and continue; if this fails for some reason, the GUI
      // will still open with default Java, six-year-old-with-a-crayon look.
      System.err.println("Problem setting UI.");
    }
//    //</editor-fold>


    /*
     Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
        new GUI().setVisible(true);
      }
    });

  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog about_dialog;
    private javax.swing.JMenuItem about_option;
    private javax.swing.JScrollPane about_scrollpane;
    private javax.swing.JTextArea about_textarea;
    private javax.swing.JButton add_button;
    private javax.swing.JButton backspace_button;
    private javax.swing.JButton c_button;
    private javax.swing.JMenuItem copy_option;
    private javax.swing.JButton divide_button;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JButton eight_button;
    private javax.swing.JButton equals_button;
    private javax.swing.JMenuItem exit_option;
    private javax.swing.JTextField expression_field;
    private javax.swing.JMenu file_menu;
    private javax.swing.JButton five_button;
    private javax.swing.JButton four_button;
    private javax.swing.JMenu help_menu;
    private javax.swing.JButton leftp_button;
    private javax.swing.JMenuBar main_menu;
    private javax.swing.JButton multi_button;
    private javax.swing.JButton nine_button;
    private javax.swing.JButton one_button;
    private javax.swing.JMenuItem paste_option;
    private javax.swing.JButton point_button;
    private javax.swing.JButton rightp_button;
    private javax.swing.JButton seven_button;
    private javax.swing.JButton six_button;
    private javax.swing.JButton sub_button;
    private javax.swing.JButton three_button;
    private javax.swing.JButton two_button;
    private javax.swing.JButton zero_button;
    // End of variables declaration//GEN-END:variables
}
