
/**
 GUI - This is the main file for the Random Sentence Generator. It
 handles all the GUI actions and utilizes the FileDialogs class, Grammar
 class, and the Sentence class to create the output.

 **We created our own Grammar called PEX2.g in the grammarFiles folder.
 It details our struggle with the creation of this PEX.

 @author C14Gavin.Delphia
 @author C14Matthew.Johnson
 @version 1.0 - Feb 13, 2012 at 10:06:08 PM
 */
import java.util.Scanner;

public class GUI extends javax.swing.JFrame {

  public static Grammar grammarData;

  /**
   Creates new form GUI
   */
  public GUI() {
    initComponents();
  }

  /**
   This method is called from within the constructor to initialize the
   form. WARNING: Do NOT modify this code. The content of this method is
   always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadBtn = new javax.swing.JButton();
        generateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSentence = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaGrammar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sentence Generator");
        setResizable(false);

        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        generateBtn.setText("Generate");
        generateBtn.setEnabled(false);
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        textAreaSentence.setColumns(20);
        textAreaSentence.setEditable(false);
        textAreaSentence.setLineWrap(true);
        textAreaSentence.setRows(5);
        textAreaSentence.setWrapStyleWord(true);
        textAreaSentence.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textAreaSentence.setSelectionColor(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(textAreaSentence);

        textAreaGrammar.setColumns(20);
        textAreaGrammar.setEditable(false);
        textAreaGrammar.setRows(5);
        textAreaGrammar.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textAreaGrammar.setSelectionColor(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(textAreaGrammar);

        jLabel1.setText("Grammar Data");

        jLabel2.setText("Generated Sentence");

        jLabel3.setText("Matthew Johnson and Gavin Delphia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generateBtn)
                            .addComponent(loadBtn))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1157)/2, (screenSize.height-628)/2, 1157, 628);
    }// </editor-fold>//GEN-END:initComponents

  /**
   Handles the code to execute when the generateBtn is interacted with.
   Creates a new sentence then outputs it to the textAreaSentence
   textField

   @param evt
   */
  private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
    Sentence sentence = new Sentence(grammarData, "<start>");
    textAreaSentence.setText(sentence.toString());
  }//GEN-LAST:event_generateBtnActionPerformed

  /**
   Handles the code to execute when the loadBtn is interacted with.
   Creates a FileDialogs to load a Grammar file then has a grammar
   created and stored in grammarData.

   @param evt
   */
  private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
    Scanner fileData = FileDialogs.selectInputFile(null);
    if (fileData != null) {
      grammarData = new Grammar(fileData);
      textAreaGrammar.setText(grammarData.toString());
      generateBtn.setEnabled(true);
      textAreaSentence.setText("");
    }
  }//GEN-LAST:event_loadBtnActionPerformed

  /**
   @param args the command line arguments
   */
  public static void main(String args[]) {
//    /*
//     Set the look and feel
//     */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//     If Nimbus (introduced in Java SE 6) is not available, stay with the
//     default look and feel. For details see
//     http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
    try {
      javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
      // Ignore exceptions and continue; if this fails for some reason, the GUI
      // will still open with default Java, six-year-old-with-a-crayon look.
      System.err.println("Problem setting UI.");
    }
//    //</editor-fold>


    /*
     Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
        new GUI().setVisible(true);
      }
    });

  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadBtn;
    private javax.swing.JTextArea textAreaGrammar;
    private javax.swing.JTextArea textAreaSentence;
    // End of variables declaration//GEN-END:variables
}
